### ISSUE TITLE
[Feat] Support `Date` and `List` standard data type for GraphAr

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#169]
**Is your feature request related to a problem? Please describe.**
As a graph format , GraphAr supports a variety of data types, including strings, numbers, and booleans. However, it does not currently support the Date and List standard data types. This issue proposes adding support for these data types to GraphAr.

Adding support for Date and Array would make GraphAr a more versatile. It would allow users to store and query dates and arrays, which are common data types in many graph database and system.

**Describe the solution you'd like**
The `Date` could use `int32` or `int64` to represent.  Just unify it in `parquet` and `orc`;
And the `List`  could be use `parquet`'s BYTE_ARRAY and `ORC`'s list;

The `serialization` and `deserialization` strategy should be define for the `Data` and `List` type.

**Additional context**
This issue is a part of issue #76  and is a good first issue for beginners to get familiar with GraphAr.

**Comment by varuntumbe** [comment]
Hi @acezen , Can I try my hands on this issue ? I might get lot of questions, will ask in discord group

Thanks

**Comment by lixueclaire** [comment]
> Hi @acezen , Can I try my hands on this issue ? I might get lot of questions, will ask in discord group
> 
> Thanks

Thanks for your interest in contributing to our project! We'd be happy to have you work on this issue.
If you have any questions or need help getting started, please don't hesitate to ask. Feel free to ask questions through issues, discussions, e-mail, or Slack. Welcome to the [GraphAr Community](https://github.com/alibaba/GraphAr/blob/main/docs/developers/community.rst), and we're looking forward to your contributions.

**Comment by acezen** [comment]
> 

Sure!,  any contribution is welcome. As @lixueclaire said, if you have any question or need help, fell free to ask~

**Comment by varuntumbe** [comment]
Thanks ! I will take like a week to kinda understand the whole thing and setup it in local, once done will ping here for more info.

Thanks and Regards 
Varun

**Comment by acezen** [comment]
The `List` data type has been support with Pull Requet #296
