### ISSUE TITLE
[Feat][DevInfra] Add test coverage to CI to measure the covering code of unitest and add banner to README

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#189]
**Is your feature request related to a problem? Please describe.**
Since GraphAr's development and code are growing,  now is the time we should add the test coverage to CI to measure  the covering code of unitest

**Describe the solution you'd like**
[ ] test coverage of C++
[ ] test coverage of Spark

**Comment by acezen** [comment]
May need to integrate some tool like:
[gcov](https://gcc.gnu.org/onlinedocs/gcc/Gcov.html) for c++

reference: https://github.com/catchorg/Catch2/issues/839

**Comment by Elssky** [comment]
I claim the task C++ test coverage

**Comment by SemyonSinchenko** [comment]
@acezen It seems to me that we forgot to add PySpark to the coverage report
