### ISSUE TITLE
[Feat][Spark] support of Spark 3.4.x and 3.5.x

### ISSUE THREAD

**Issue by SemyonSinchenko** [apache/incubator-graphar#381]
**Is your feature request related to a problem? Please describe.**
Currently only 3.2.x and 3.3.x versions are supported.

**Describe the solution you'd like**
- `datasources-34` submodule in spark project
- `datasources-34` profile in top level pom.xml
- new version in spark CI `matrix`

**Describe alternatives you've considered**
.

**Additional context**
Existent `datasources-32` and `datasources-33` may be used as an example.

**Comment by SemyonSinchenko** [comment]
@ShockleysxX sure. Let me know if you need some help here.

**Comment by acezen** [comment]
Hi, @ShockleysxX Do you have any progress on this issue, or do you need any help?

**Comment by acezen** [comment]
The permalink to the related code
- `datasources-34` submodule in spark project
  this can refer to the [datasource-32](https://github.com/apache/incubator-graphar/tree/main/spark/datasources-32) and [datasource-33](https://github.com/apache/incubator-graphar/tree/main/spark/datasources-33)
- `datasources-34` profile in top level pom.xml
https://github.com/apache/incubator-graphar/blob/f0ae38a81401b9d873a3a8575f83ec5edaef93a1/spark/pom.xml#L37-L81
- new version in spark CI `matrix`
https://github.com/apache/incubator-graphar/blob/f0ae38a81401b9d873a3a8575f83ec5edaef93a1/.github/workflows/spark.yaml#L45-L52

**Comment by SemyonSinchenko** [comment]
@ShockleysxX Do you need any kind of help with this issue?

**Comment by xin-hao-awx** [comment]
can we also add the 3.5.x or even 4.0.x to the roadmap?
