### ISSUE TITLE
[Infra] IP Clearance and Code Cleanup

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#430]
*This issue is used for describing the work of IP Clearance and Code Cleanup for [code initial import](https://incubator.apache.org/guides/transitioning_asf.html) into apache repo.*

### IP Clearance
We have done Qingyuan SCA scan from inner tool.

**Qingyuan SCA scan result**
<img width="526" alt="qingyuan-sca-result" src="https://github.com/alibaba/GraphAr/assets/11835645/e96c35f2-ae7e-4e93-b8d4-3d1b4e4d2183">

Note: The only medium-risk level of third-party licensing is that GraphAr uses JUnit 4 (under the EPL-1.0 license) as the Java unit testing framework.

### Code Cleanup
We have done skywalking-eyes scan and integrated skywalking-eyes chack in our CI progress.

**skywalking-eyes scan result**
<img width="1088" alt="skywalking-eye-result" src="https://github.com/alibaba/GraphAr/assets/11835645/9596aa2d-4229-4c52-9d3f-0cec73c28c9a">

**Comment by CalvinKirs** [comment]
Third Party Licensing Policy: https://www.apache.org/legal/resolved.html 
For binary dependencies, JUnit (EPL)is a perfectly viable option. check here:
https://www.apache.org/legal/resolved.html#binary-only-inclusion-condition

**Comment by acezen** [comment]
> Third Party Licensing Policy: https://www.apache.org/legal/resolved.html For binary dependencies, JUnit (EPL)is a perfectly viable option. check here: https://www.apache.org/legal/resolved.html#binary-only-inclusion-condition

Thanks for the clarification:)
