### ISSUE TITLE
[Feat][C++] Support validating the null value in high level

### ISSUE THREAD

**Issue by jasinliu** [apache/incubator-graphar#434]
**Is your feature request related to a problem? Please describe.**
Currently, we can only get the null value which is already been casted in high level.
Like this. The null value is casted to 0.
![image](https://github.com/alibaba/GraphAr/assets/85552719/537f7662-5f3e-45c9-b696-75c4426f67cf)
![image](https://github.com/alibaba/GraphAr/assets/85552719/fbe3943c-7d86-4573-aefe-ad11e43a47b5)

**Describe the solution you'd like**
Do we need to support validating the null value in high level?
Like the arrow.[IsValid](https://arrow.apache.org/docs/cpp/api/array.html#_CPPv4NK5arrow5Array7IsValidE7int64_t)

**Comment by acezen** [comment]
@jasinliu thanks. it seems that the high level reader does need to support such feature to check the property of vertex or edge is valid or not. I will look up the code to check out how to implement is good for current APIs ASAP.

**Comment by jasinliu** [comment]
> @jasinliu thanks. it seems that the high level reader does need to support such feature to check the property of vertex or edge is valid or not. I will look up the code to check out how to implement is good for current APIs ASAP.

Wow, the reply is so fast. I just create the pr. Thanks very much~

**Comment by acezen** [comment]
close as solved.
