### ISSUE TITLE
[Spark-java-refactor] Split java-info to a single submodule

### ISSUE THREAD

**Issue by Thespica** [apache/incubator-graphar#445]
**Is your feature request related to a problem? Please describe.**
As we discussed in our weekly meeting, it would be better to split java-info to a single submodule behind spark(maybe need to rename?) parent module. 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by acezen** [comment]
the discussion note can find in [GraphAr meeting note(2024-04-09)](https://docs.google.com/document/d/1fzMW_6lzTbR0YGa3C0pY3ca_ZYuPSBkmrNtfWXlnYr8/edit#heading=h.k1ts4kvvl8jq)
