### ISSUE TITLE
feat(c++): Use C++17's nested namespaces

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#473]
### Describe the enhancement requested

Clang-tidy prefers it. It is more compact and now that we are on C++ 17 I don't see any reason we shouldn't move everything over.

Before:
```c++
namespace graphar {
namespace util {
```

After:
```c++
namespace graphar::util {
```

### Component(s)

C++

**Comment by ywh555hhh** [comment]
Hello, I'm interested in taking on this issue. I understand it involves implementing cleaner code. Could you please assign it to me? Thank you.

**Comment by lixueclaire** [comment]
> Hello, I'm interested in taking on this issue. I understand it involves implementing cleaner code. Could you please assign it to me? Thank you.

Sure, the issue has been assigned to you. Thank you for your interest, and we are looking forward to your contribution.

**Comment by ywh555hhh** [comment]
Hello, I have a question. In the case where we have code in the `graphar` namespace but not in any nested namespace (like the `Status` class functions), should we still modify the namespace to use the C++17 nested namespace syntax? From my understanding, using the new syntax wouldn't reduce the nesting in this case. Could you please clarify this? Thank you.

[here](https://github.com/apache/incubator-graphar/blob/87d5eeb6a7f86574328da26f08d950e3c5bc3de8/cpp/include/graphar/util/status.h#L64)

**Comment by lixueclaire** [comment]
> Hello, I have a question. In the case where we have code in the `graphar` namespace but not in any nested namespace (like the `Status` class functions), should we still modify the namespace to use the C++17 nested namespace syntax? From my understanding, using the new syntax wouldn't reduce the nesting in this case. Could you please clarify this? Thank you.
> 
> [here](https://github.com/apache/incubator-graphar/blob/87d5eeb6a7f86574328da26f08d950e3c5bc3de8/cpp/include/graphar/util/status.h#L64)

Hi, I think you could separate the code and re-org them using the new style, like:
```
namespace graphar::util {
...
}

namespace graphar {
...
}
```

**Comment by ywh555hhh** [comment]
Can this issue be closed?

**Comment by acezen** [comment]
yes, thanks for @ywh555hhh 's work,  the issue has been resolved.
