### ISSUE TITLE
[java-info] Merge java-info code into main by components step by step

### ISSUE THREAD

**Issue by Thespica** [apache/incubator-graphar#478]
### Describe the enhancement requested

Now, the java-info code basically has been completed in [this branch](https://github.com/apache/incubator-graphar/tree/branch-feat-spark-java-info-refactoring). I am going to merge these code into main branch by components step by step:
- [x] basic architecture(including pom.xml and directory), yaml, type and util
- [x] small class like Property and AdjacentList
- [x] graph, vertex and edge info

### Component(s)

Format, Java, Spark

**Comment by SemyonSinchenko** [comment]
May we postpone that until we decide with proto?
(see #475 and discussion in mailing list)

**Comment by Thespica** [comment]
Hi @SemyonSinchenko , I think this two missions are relatively independent, the merge won't effect the decision about proto.

**Comment by acezen** [comment]
> May we postpone that until we decide with proto? (see #475 and discussion in mailing list)

I think is ok to migrate the current implementation from branch-feat-spark-java-info-refactoring to main. when the discussion about protobuf is done, we can refactoring the module base the main.
