### ISSUE TITLE
fix(infra): Fix the invalid dev container image

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#490]
### Describe the bug, including details regarding any error messages, version, and platform.

The image in dev container config
https://github.com/apache/incubator-graphar/blob/87d5eeb6a7f86574328da26f08d950e3c5bc3de8/.devcontainer/devcontainer.json#L25
is invalid and can not be pulled since it is a private image.

make the image public, and it's better to put it in docker hub.

### Component(s)

Developer Tools

**Comment by ywh555hhh** [comment]
docker pull registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev:latest
Error response from daemon: pull access denied for registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

There are still something wrong

**Comment by ywh555hhh** [comment]
docker pull registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev:latest
Error response from daemon: pull access denied for registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

There are still something wrong

**Comment by acezen** [comment]
> docker pull registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev:latest Error response from daemon: pull access denied for registry.cn-hongkong.aliyuncs.com/graphscope/graphar-dev, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> 
> There are still something wrong

Oh, I forgot to update the initializeCommand! thanks for pointing out
 https://github.com/apache/incubator-graphar/blob/70e92d9b79b831eac7bc2c3f17ba7ff6140dc65a/.devcontainer/devcontainer.json#L54 has not been updated?

**Comment by ywh555hhh** [comment]
I just tried it, and it's working
