### ISSUE TITLE
Improve the building process and contributing document for developer to easily building the libraries from scratch

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#495]
### Describe the enhancement requested

Current building process and contributing document of libraries is scattered and not friendly and clear for newcome.

Try to improve the building process and contributing document in these aspects:

- Provide a general building process of all libraries in contributing guide.
- If the dependencies is complex, maybe provide helper scripts to install dependency.
- improve the dev container image for easy access a virtual develop environment
- Make the contributing document clear and understandable for newcome

### Component(s)

Documentation

**Comment by acezen** [comment]
Hi, @ywh555hhh @amygbAI, as the new contributor for GraphAr, are there any suggestions or problem you have when came cross the getting-start of GraphAr development? We would be very happy to get feedbacks from you.

**Comment by amygbAI** [comment]
thanks for asking .. i think on the whole the project is quite well documented BUT they are placed within specific folders. So imho that you can 

1. have it in the main page README itself ( as different sections )
2. testing instructions about where to access sample test files, where to put it into a repository , what versions of the softwares we need to test in ( for e.g. spark versions ) 
3. code formatting instructions ( what commands to run etc ) 

but otherwise i think the team behind this project is quite tuned into the project and make noobs like me feel welcome :)

**Comment by acezen** [comment]
> thanks for asking .. i think on the whole the project is quite well documented BUT they are placed within specific folders. So imho that you can
> 
> 1. have it in the main page README itself ( as different sections )
> 2. testing instructions about where to access sample test files, where to put it into a repository , what versions of the softwares we need to test in ( for e.g. spark versions )
> 3. code formatting instructions ( what commands to run etc )
> 
> but otherwise i think the team behind this project is quite tuned into the project and make noobs like me feel welcome :)

Thanks for the the reply, the suggestions are very helpful!

**Comment by ywh555hhh** [comment]
Firstly, thank you for asking! Here are my suggestions:

1. Tips for development containers: Using development containers to assist rookies is a great idea. However, rookies might not know how to use them. Providing tips or recommendations would be helpful. For example, in the (graphscope) project's developer guide, I learned how to use the VSCode Remote plugin with development containers. Posting links to related tutorials could also be beneficial.

2. Local testing guidance: I prefer to test locally before submitting a Pull Request (PR) to respect the community managers' time. If I can identify and fix issues through local testing, it saves them trouble. However, I haven't found a tutorial for local testing.

3. Different developer guides: I suggest having separate developer guides for rookies and veterans. This way, rookies won't be confused by too concise instructions, and veterans won't be overwhelmed by too much information.

These are my current suggestions. If I have more in the future, I'd be happy to share again.

Also, I'd like to offer my help in creating a developer guide for rookies. As a rookie, I understand their needs best.

**Comment by acezen** [comment]
> Firstly, thank you for asking! Here are my suggestions:
> 
> 1. Tips for development containers: Using development containers to assist rookies is a great idea. However, rookies might not know how to use them. Providing tips or recommendations would be helpful. For example, in the (graphscope) project's developer guide, I learned how to use the VSCode Remote plugin with development containers. Posting links to related tutorials could also be beneficial.
> 2. Local testing guidance: I prefer to test locally before submitting a Pull Request (PR) to respect the community managers' time. If I can identify and fix issues through local testing, it saves them trouble. However, I haven't found a tutorial for local testing.
> 3. Different developer guides: I suggest having separate developer guides for rookies and veterans. This way, rookies won't be confused by too concise instructions, and veterans won't be overwhelmed by too much information.
> 
> These are my current suggestions. If I have more in the future, I'd be happy to share again.
> 
> Also, I'd like to offer my help in creating a developer guide for rookies. As a rookie, I understand their needs best.

Thanks for the suggestions. It would be helpful if you can help to draft a developer guide for new contributor. You can start from C++ library.

**Comment by ywh555hhh** [comment]
> > Firstly, thank you for asking! Here are my suggestions:
> > 
> > 1. Tips for development containers: Using development containers to assist rookies is a great idea. However, rookies might not know how to use them. Providing tips or recommendations would be helpful. For example, in the (graphscope) project's developer guide, I learned how to use the VSCode Remote plugin with development containers. Posting links to related tutorials could also be beneficial.
> > 2. Local testing guidance: I prefer to test locally before submitting a Pull Request (PR) to respect the community managers' time. If I can identify and fix issues through local testing, it saves them trouble. However, I haven't found a tutorial for local testing.
> > 3. Different developer guides: I suggest having separate developer guides for rookies and veterans. This way, rookies won't be confused by too concise instructions, and veterans won't be overwhelmed by too much information.
> > 
> > These are my current suggestions. If I have more in the future, I'd be happy to share again.
> > Also, I'd like to offer my help in creating a developer guide for rookies. As a rookie, I understand their needs best.
> 
> Thanks for the suggestions. It would be helpful if you can help to draft a developer guide for new contributor. You can start from C++ library.

Can I open a PR to sync this with the community?

**Comment by acezen** [comment]
> > > Firstly, thank you for asking! Here are my suggestions:
> > > 
> > > 1. Tips for development containers: Using development containers to assist rookies is a great idea. However, rookies might not know how to use them. Providing tips or recommendations would be helpful. For example, in the (graphscope) project's developer guide, I learned how to use the VSCode Remote plugin with development containers. Posting links to related tutorials could also be beneficial.
> > > 2. Local testing guidance: I prefer to test locally before submitting a Pull Request (PR) to respect the community managers' time. If I can identify and fix issues through local testing, it saves them trouble. However, I haven't found a tutorial for local testing.
> > > 3. Different developer guides: I suggest having separate developer guides for rookies and veterans. This way, rookies won't be confused by too concise instructions, and veterans won't be overwhelmed by too much information.
> > > 
> > > These are my current suggestions. If I have more in the future, I'd be happy to share again.
> > > Also, I'd like to offer my help in creating a developer guide for rookies. As a rookie, I understand their needs best.
> > 
> > 
> > Thanks for the suggestions. It would be helpful if you can help to draft a developer guide for new contributor. You can start from C++ library.
> 
> Can I open a PR to sync this with the community?

Yes, feel free to open a sub-issue and PR for the work

**Comment by ywh555hhh** [comment]
hi , I also mentioned some of my thoughts on developer containers in this [discussion#501](https://github.com/apache/incubator-graphar/discussions/501)
