### ISSUE TITLE
[Feat][CI] Enable markdownlint and typos in Graphar Doc workflow

### ISSUE THREAD

**Issue by ywh555hhh** [apache/incubator-graphar#499]
### Describe the enhancement requested

In the workflows/docs. yml file, there are some TODO item has not been completed. Someone needs to complete these TODO items.
[here](https://github.com/apache/incubator-graphar/blob/f3aeccbd331483fdc144edc6d61f22d686ed5d35/.github/workflows/docs.yml#L78C1-L78C36)

### Component(s)

Continuous Integration

**Comment by acezen** [comment]
Hi, @ywh555hhh, Do you want to help to implement the feature?

**Comment by ywh555hhh** [comment]
I can try, but I may not start until next week. This week, I am preparing the application for CLI for GraphAr project

**Comment by acezen** [comment]
> I can try, but I may not start until next week. This week, I am preparing the application for CLI for GraphAr project

Thanks very much. This is not urgent issue so it'ok to work on your own schedule and feel free to ask if you have any question.
