### ISSUE TITLE
[Bug][C++][Test][Docker] Test Failure: Subprocess Terminated Due to Missing `/etc/localtime` Time Zone File in dev container

### ISSUE THREAD

**Issue by ywh555hhh** [apache/incubator-graphar#502]
### Describe the bug, including details regarding any error messages, version, and platform.

**Description:**

In the developer container, after building `build-debug` with the `cpp` library without modifying any code, an attempt to run the test `test_orc_and_parquet_reader` failed. The error message is as follows:

```
ValueOrDie called on an error: Unknown error: Time zone file /etc/localtime does not exist. Please install IANA time zone database and set TZDIR env.
```

**Resolution Steps:**

1. Install the IANA time zone database:
   ```bash
   sudo apt-get install tzdata
   ```

2. Set the environment variable `TZDIR` to point to the location of the IANA time zone database:
   ```bash
   export TZDIR=/usr/share/zoneinfo
   ```

After performing the above steps, the test can pass normally.

**Issue:**

The developer container should provide a ready-to-use environment for developers to complete all tests normally. Currently, the container is missing the necessary time zone file, which does not meet the expected purpose of the developer container.

**Expectation:**

The developer container should include a complete IANA time zone database when distributed, ensuring that all tests can run without additional configuration.

**Notes:**

- The test failure occurred after building `build-debug`.
- The test `test_orc_and_parquet_reader` failed due to the absence of the `/etc/localtime` time zone file.
- After manually installing the IANA time zone database and setting the environment variable `TZDIR`, the test can pass normally.

### Component(s)

C++, Developer Tools

**Comment by acezen** [comment]
Thanks for reporting, this will be fix as part of dev container image improvement as #495
