### ISSUE TITLE
[Feat][Format][Java][Spark] Incorporate maven-proto-plugin into build of Maven projects

### ISSUE THREAD

**Issue by SemyonSinchenko** [apache/incubator-graphar#522]
### Describe the enhancement requested

Based on the discussion in a dev-list it should be a separate subproject.

### Component(s)

Format, Java, Spark

**Comment by Thespica** [comment]
Hi @SemyonSinchenko 

I am available recently, wanting to help incorporating the java-info part.

 Have you finished the part of java-info? If you haven't start for this part, can you assign it to me?
