### ISSUE TITLE
docker image for the dev container cannot be pulled in mainland.

### ISSUE THREAD

**Issue by yecol** [apache/incubator-graphar#537]
### Describe the enhancement requested

Since the dockerhub is hard to access in mainland, the image cannot be pulled. 
Is that possible to put the docker image in the github registry (ghcr.io)? 
This should be more friendly to developers both in/outside of mainland.

### Component(s)

Developer Tools

**Comment by acezen** [comment]
Thanks for the advice. I would try to move the docker image to ghcr.io and update the `devcontainer.json`.

**Comment by acezen** [comment]
> Thanks for the advice. I would try to move the docker image to ghcr.io and update the `devcontainer.json`.

The `graphar-dev` image has been push to both [dockerhub](https://hub.docker.com/r/apache/graphar-dev) and [ghcr.io](https://github.com/apache/incubator-graphar/pkgs/container/graphar-dev)

Hi, @yecol , could you help to update the `devcontainer.json` to the github registry?
https://github.com/apache/incubator-graphar/blob/28edb931f897ae3465501e94bba900b876c7b0d9/.devcontainer/devcontainer.json#L25

**Comment by yecol** [comment]
Sure, I will do it.
