### ISSUE TITLE
[Feat][C++] Support static installation of arrow and graphar

### ISSUE THREAD

**Issue by jasinliu** [apache/incubator-graphar#538]
### Describe the enhancement requested

Currently, GraphAr C++ supports dynamic installation, but not static installation. Arrow entry is also a dynamic method. 

Two cmake options can be added to support static installation, giving users better choices.

### Component(s)

C++

**Comment by acezen** [comment]
Could you add some scenario description that why you need arrow static in your use case?

**Comment by jasinliu** [comment]
> Could you add some scenario description that why you need arrow static in your use case?

Arrow's static installation can reduce application deployment cost.

**Comment by acezen** [comment]
arrow already provide static [installation](https://arrow.apache.org/install/) or compilation(https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/building.rst)
I think we can provide a CMake option to enable linking arrow static library.

**Comment by jasinliu** [comment]
> arrow already provides static [installation](https://arrow.apache.org/install/) or compilation(https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/building.rst) I think we can provide a CMake option to enable linking arrow static library.
> 
> Is that meets the issue requirement?

Yes. And another cmake option to enable build static graphar.

**Comment by acezen** [comment]
> > arrow already provides static [installation](https://arrow.apache.org/install/) or compilation(https://github.com/apache/arrow/blob/main/docs/source/developers/cpp/building.rst) I think we can provide a CMake option to enable linking arrow static library.
> > Is that meets the issue requirement?
> 
> Yes. And another cmake option to enable build static graphar.

great, I think that looks OK to me. Would you have interest to take this task? I think add only several lines of code to CMakeList is OK for this issue

**Comment by jasinliu** [comment]
Of course, I want have a try!

**Comment by acezen** [comment]
> Of course, I want have a try!

That's very appreciated. I have assigned you. Feel free to ask for help if you have any problem.
