### ISSUE TITLE
feat(c++): Raise error in CMakeList.txt if arrow does not support ORC

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#545]
### Describe the enhancement requested

Sometimes the installed arrow dependency does not support ORC. For example, current homebrew apache-arrow package [does not include ORC support](https://github.com/Homebrew/homebrew-core/blob/3e5bcaebc162335f428571a4cb0277fcdb35886d/Formula/a/apache-arrow.rb#L52)

We need to add a check to CMakeList, raise error if the arrow does not support ORC.

### Component(s)

C++

**Comment by acezen** [comment]
The best way to check that ORC support or not is check the `ARROW_ORC` variable after `find_package(Arrow)`.

**Comment by yecol** [comment]
Thanks for your hint! I will try.
