### ISSUE TITLE
Dependency arrow/orc not installed by brew on macOS

### ISSUE THREAD

**Issue by yecol** [apache/incubator-graphar#547]
### Describe the bug, including details regarding any error messages, version, and platform.

It seems we have recognized this problem as shown in the cpp/README.md.
> Note: Currently, the Arrow C++ library is [disable ARROW_ORC](https://github.com/Homebrew/homebrew-core/blob/4588359b7248b07379094de5310ee7ff89afa17e/Formula/a/apache-arrow.rb#L53) in the brew formula, so you need to install the Arrow C++ library manually.

However, the given solution seems does not fix the problem. 
Since in the `cpp/Brewfile`, it still just simply `install apache-arrow`

### Component(s)

C++, Developer Tools

**Comment by acezen** [comment]
We suppose to fix that by #545 #546
