### ISSUE TITLE
bug(c++): arrow reader corner case

### ISSUE THREAD

**Issue by jasinliu** [apache/incubator-graphar#549]
### Describe the enhancement requested

When we use reader->GetChunk(), if the directory starts with part1, we can not get the chunk. But next_chunk() is fine. If we don’t know the directory, we don't know wheher we need use next_chunk().

Example: neo4j/edge/Person_REVIEWED_Movie/ordered_by_source/adj_list/**part1**.
https://github.com/apache/incubator-graphar-testing/tree/main/neo4j/edge/Person_REVIEWED_Movie/ordered_by_source

### Component(s)

C++

**Comment by acezen** [comment]
Thanks for the report, I will take care of this bug.

**Comment by jasinliu** [comment]
Minimal reproduction process https://gist.github.com/jasinliu/e7d20688fcbc17de22fb3b6fa13eb59d

![QQ_1721820477740](https://github.com/user-attachments/assets/78e70db2-44e6-4a1f-b416-167f848278ab)

**Comment by jasinliu** [comment]
Oh, this is my question. 

We need to know a premise: the first chunk can be empty. Then make a judgment through `has_value()` to decide whether to switch to the next chunk.

**Comment by acezen** [comment]
Reopen since we suppose to return nullptr if the edge of the vertex chunk is empty.

**Comment by acezen** [comment]
done
