### ISSUE TITLE
feat(scala): Support S3 reading/writing 

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#570]
### Describe the enhancement requested
Currently the Scala SDK does not support S3 
```
org.apache.hadoop.fs.UnsupportedFileSystemException: No FileSystem for scheme "s3"
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3443)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
  at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
  at org.apache.graphar.GraphInfo$.loadGraphInfo(GraphInfo.scala:379)
  at org.apache.graphar.GraphInfoSuite.$anonfun$new$2(TestGraphInfo.scala:49)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
```

Add related dependencies to enable S3 reading and writing.

### Component(s)

Spark

**Comment by SemyonSinchenko** [comment]
Did you check [this part](https://spark.apache.org/docs/latest/cloud-integration.html#committing-work-into-cloud-storage-safely-and-fast) of spark docs? Which version of Hadoop are you using?

**Comment by SemyonSinchenko** [comment]
May you give a code example?

**Comment by acezen** [comment]
> May you give a code example?

Hi Sem, I try to print the hadoop version and got `3.3.1`.

You can check the code [s3-test](https://github.com/acezen/GraphAr/blob/69cdab235e8b2c7afcd3aae96c9f25824332b3b4/maven-projects/spark/graphar/src/test/scala/org/apache/graphar/TestGraphInfo.scala#L48-L53)

and run it with `mvn test -Dsuites="org.apache.graphar.GraphInfoSuite load graph info s3"`

**Comment by SemyonSinchenko** [comment]
May you try s3a instead of s3?

**Comment by acezen** [comment]
> May you try s3a instead of s3?

You mean change the path from `s3://graphar-data/ldbc.graph.yml` to `s3a://graphar-data/ldbc.graph.yml`?

**Comment by acezen** [comment]
> > May you try s3a instead of s3?
> 
> You mean change the path from `s3://graphar-data/ldbc.graph.yml` to `s3a://graphar-data/ldbc.graph.yml`?

I just tried it and got error that `Class org.apache.hadoop.fs.s3a.S3AFileSystem not found`:

```
- load graph info s3 *** FAILED ***
  java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
  at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2667)
  at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
  at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
  at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
  at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
  at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
  at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
  at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
  at org.apache.graphar.GraphInfo$.loadGraphInfo(GraphInfo.scala:379)
  at org.apache.graphar.GraphInfoSuite.$anonfun$new$2(TestGraphInfo.scala:52)
```

**Comment by SemyonSinchenko** [comment]
I think the reason is that GraphAr Spark relying on a custo implementation of Hadoop (`com.aliyun`). My current guess is that an implementation of S3A commiter is not included in the "hadoop-oss" build we are using. Let me check it.

**Comment by SemyonSinchenko** [comment]
Ok, there is actually no s3a implementation. To bypass it it should be enough to add `hadoop-aws` JAR (https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws) to `"${HOME}/${{ matrix.spark-hadoop }}/jars" folder (`${SPARK_HOME}/jars`). I checked, the JAR is actually there.

For development we can add it constantly to JARs folder. But I do not like an idea of adding it to the distribution cause it may tends to dependency hell...

![image](https://github.com/user-attachments/assets/2313a53a-a82c-415a-8122-8b80a7b02a23)

**Comment by SemyonSinchenko** [comment]
Documentation of Apache Spark directly mentioned that case:
> Commercial products based on Apache Spark generally directly set up the classpath for talking to cloud infrastructures, in which case this module may not be needed.

**Comment by SemyonSinchenko** [comment]
![image](https://github.com/user-attachments/assets/d4acdd78-7e15-4aec-8897-a943482360a0)
I think with `hadoop-aws` in CP it should also work with `s3n`. May you try it? `s3n` is a next generation of s3-commiters for Spark.

**Comment by acezen** [comment]
> Ok, there is actually no s3a implementation. To bypass it it should be enough to add `hadoop-aws` JAR (https://mvnrepository.com/artifact/org.apache.hadoop/hadoop-aws) to `"${HOME}/${{ matrix.spark-hadoop }}/jars"` folder (`${SPARK_HOME}/jars`). I checked, the JAR is actually there.
> 
> For development we can add it constantly to JARs folder. But I do not like an idea of adding it to the distribution cause it may tends to dependency hell...
> 
> ![image](https://private-user-images.githubusercontent.com/29755009/353788752-2313a53a-a82c-415a-8122-8b80a7b02a23.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQwNDMsIm5iZiI6MTcyMjQyMzc0MywicGF0aCI6Ii8yOTc1NTAwOS8zNTM3ODg3NTItMjMxM2E1M2EtYTgyYy00MTVhLTgxMjItOGI4MGE3YjAyYTIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMDc2ZTczNGQ2Nzg5YzgyOGRkYjY1M2VmZDBlODdlMWFkODgzYTI4YzYxMTQ5OWQxYTJlOTMyYTY2NDcxOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ofq_PyMdk5f_hbywaIwxk46gSaOkMEcnnPZHW1RYSU4)

So I think we can add some guide to document to tell the user that if they want to use s3, they need to add `hadoop-aws` by themselves?

**Comment by acezen** [comment]
> ![image](https://private-user-images.githubusercontent.com/29755009/353790193-d4acdd78-7e15-4aec-8897-a943482360a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MjQwNDMsIm5iZiI6MTcyMjQyMzc0MywicGF0aCI6Ii8yOTc1NTAwOS8zNTM3OTAxOTMtZDRhY2RkNzgtN2UxNS00YWVjLTg4OTctYTk0MzQ4MjM2MGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDExMDIyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMGJlMjVlZGU5Y2M4MTNiNzI2ZWRjM2JhMDY4ZDFiMzI1NmMxZTg2NTMyMTc3OWQ4YTcwMTU0ZTllMTdkMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K9J_OUv5jbtr4g3afWu3Dv3CeKpNEAIJfAIsHRC_34E) I think with `hadoop-aws` in CP it should also work with `s3n`. May you try it? `s3n` is a next generation of s3-commiters for Spark.

Yes, I can try it .

**Comment by acezen** [comment]
> > So I think we can add some guide to document to tell the user that if they want to use s3, they need to add hadoop-aws by themselves?
> 
> What do you think about reference to the documentation of Apache Spark itself? Because otherwise it may be confusing. Most of spark distributions (like Databricks Runtime, Microsoft Fabric, EMR, Cludera Spark, etc.) already contains all the dependencies needed for integration with the corresponding cloud provider. This dependencies are often proprietary and adding an OSS `hadoop-aws` may tend to unpredictable behaviour.
> 
> [This section](https://hadoop.apache.org/docs/current/hadoop-aws/tools/hadoop-aws/index.html) of Hadoop Documentation is very detailed.

Make sense to me. I can open a PR and add the document as reference.

**Comment by SemyonSinchenko** [comment]
@acezen I think we may also update a dev-container by adding all the spark dependencies for development, including `hadoop-aws` to simplify development for people not familiar with all these Hadoop ecosystem.
