### ISSUE TITLE
feat(ci): avoid running CI if pull request is still working in progress

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#602]
### Describe the enhancement requested

To save the quota of CI resource, I suggest to avoid running CI when PR is still working in progress

we can refer to  [arrow's configuration]( https://github.com/apache/arrow/blob/9fc03015463a8f1cb616b088342b104fbc767a0c/.github/workflows/cpp.yml#L119)

### Component(s)

Continuous Integration

**Comment by SemyonSinchenko** [comment]
Another option is to run CI in the user's git instead of org git. Like it is done in Apache Spark when actions are running in PR author's git: https://github.com/apache/spark/blob/master/.github/workflows/notify_test_workflow.yml#L38

**Comment by Thespica** [comment]
for reference: not only check `wip` field in PR, but also check PR status by `if: github.event.pull_request.draft == false`.

form discussion here: https://github.com/orgs/community/discussions/25722

**Comment by Thespica** [comment]
BTW, @acezen 

Can you refine maven log with `-q` option like [what GraphScope do](https://github.com/alibaba/GraphScope/blob/c7b3f35263cc8a2b652781959814156efdca223a/.github/workflows/interactive.yml#L147) with this feat together?

**Comment by SemyonSinchenko** [comment]
> Could you refine maven log with `-q` option like [what GraphScope do](https://github.com/alibaba/GraphScope/blob/c7b3f35263cc8a2b652781959814156efdca223a/.github/workflows/interactive.yml#L147) with this feat together?

I do not like `-q`. We already made Maven logs much more readable by `--no-transfer-progress` but `-q` means that there were zero logs. Do we actually need it?

**Comment by Thespica** [comment]
> > Could you refine maven log with `-q` option like [what GraphScope do](https://github.com/alibaba/GraphScope/blob/c7b3f35263cc8a2b652781959814156efdca223a/.github/workflows/interactive.yml#L147) with this feat together?
> 
> I do not like `-q`. We already made Maven logs much more readable by `--no-transfer-progress` but `-q` means that there were zero logs. Do we actually need it?

Thanks Sem, I ignored that we have already add the `--no-transfer-progress` option. Current situation is enough.

**Comment by yecol** [comment]
Github PR draft is designed for this.

Just open this as admin.

<img width="707" alt="Screenshot 2024-08-22 at 10 56 13 AM" src="https://github.com/user-attachments/assets/f103cc37-ca3c-44fc-a6ab-581d2d17eed6">

**Comment by acezen** [comment]
> Github PR draft is designed for this.
> 
> Just open this as admin.
> 
> <img alt="Screenshot 2024-08-22 at 10 56 13 AM" width="707" src="https://private-user-images.githubusercontent.com/426463/360231651-f103cc37-ca3c-44fc-a6ab-581d2d17eed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODIyNzAsIm5iZiI6MTcyNDM4MTk3MCwicGF0aCI6Ii80MjY0NjMvMzYwMjMxNjUxLWYxMDNjYzM3LWNhM2MtNDRmYy1hNmFiLTU4MWQyZDE3ZWVkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwMjU5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGVhMTFlMGIyMThhYzQzMDA4YzFjZWY4MGFkYjRjNWZkYmU2ZjMzNTNiNzYxMGNlNGFhZDkxNmVlOWQzN2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QMnbzqoh_qc7AuIEo1O6UFzAQF6JlyGxmvb6R8Ja7q8">

This looks perfect for this feat, I'll try to ask infra team to open `Try draft pull request` for GraphAr.

**Comment by acezen** [comment]
> > Github PR draft is designed for this.
> > Just open this as admin.
> > <img alt="Screenshot 2024-08-22 at 10 56 13 AM" width="707" src="https://private-user-images.githubusercontent.com/426463/360231651-f103cc37-ca3c-44fc-a6ab-581d2d17eed6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzODIyNzAsIm5iZiI6MTcyNDM4MTk3MCwicGF0aCI6Ii80MjY0NjMvMzYwMjMxNjUxLWYxMDNjYzM3LWNhM2MtNDRmYy1hNmFiLTU4MWQyZDE3ZWVkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyM1QwMjU5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGVhMTFlMGIyMThhYzQzMDA4YzFjZWY4MGFkYjRjNWZkYmU2ZjMzNTNiNzYxMGNlNGFhZDkxNmVlOWQzN2NmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QMnbzqoh_qc7AuIEo1O6UFzAQF6JlyGxmvb6R8Ja7q8">
> 
> This looks perfect for this feat, I'll try to ask infra team to open `Try draft pull request` for GraphAr.

It seems that draft pull request still trigger the CI, like https://github.com/apache/incubator-graphar/pull/606, I suggest that we can add  check as @Thespica said.
