### ISSUE TITLE
feat(format): Change the naming of vertex/edge type from `label` to `type`

### ISSUE THREAD

**Issue by acezen** [apache/incubator-graphar#604]
### Describe the enhancement requested

Since we plan to support [multiple labels of vertex and edge](https://github.com/apache/incubator-graphar/issues/96). And currently we use the `label` as the unique type of vertex/edge, but it would make confusion with the multi-label in the future.

So it's better to make the `type` as the unique type of vertex/edge and let `label` be the multi-label.

### Component(s)

Format

**Comment by Elssky** [comment]
I submitted this change

**Comment by acezen** [comment]
> I submitted this change

Thanks for the contribution.
